import type { Metadata } from "next";
import { Locale, i18n } from '../../i18n.config'
import localFont from "next/font/local";

import "@repo/tailwind-config/styles.css"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale }
}>) {
  console.log('lang',params)
  return (
    <html lang={params.lang}>
      <body className={`dark p-4`}>
        {children}
      </body>
    </html>
  );
}
